# Настройки сервера
server:
  port:

spring:
  # Настройка RabbitMQ
  rabbitmq:
    host: localhost
    port:
    username:
    password:
    virtual-host:
  # Настройка соединения с базой данных Postgres
  datasource:
    username:
    password:
    url:
  jpa:
    generate-ddl: true
    show-sql: true

# Настройка логирования
logging:
  level:
    org.springframework: ERROR
    org.telegram: ERROR
    ru.zerrbild: DEBUG
  pattern:
    console: "%d %highlight(%5level) %clr(${PID}){magenta} --- [%17.17t] %clr(%-40logger{36}){cyan} :: %clr(%-30.30method){yellow} : %msg%n"
    file: "%d %5p ${PID} --- [%t] %-60c{1.} : %m%n"
  file:
    name: ./logs/message-handler.log

# Названия очередей, обменов и связываний
rabbitmq:
  queue:
    text: text
    document: document
    image: image
    response: response
    registrants:
      name: registrants
      ttl: 3600000
    deregister_candidates: deregister_candidates
  exchange:
    message:
      name: message
      routing_key:
        to_response_queue: response
    user:
      name: user
      routing_key:
        to_registrants_queue: registrants
        to_deregister_candidates_queue: candidates
# Ссылки для получения информации о файле и его скачивания c серверов Telegram
telegram:
  bot_token:
  uri:
    file_info: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
    file_download: https://api.telegram.org/file/bot{token}/{filePath}

link:
  protocol:
  address:
  encryption_key:
  port:
    rest_service:
    mail_service: